services:
  postgres:
    image: postgres:latest
    container_name: weather-postgres
    restart: always
    environment:
      POSTGRES_USER: weather
      POSTGRES_PASSWORD: weather
      POSTGRES_DB: weather
    ports:
      - "5432:5432"
    volumes:
      - weather_pgdata:/var/lib/postgresql/data

volumes:
  weather_pgdata: